# Codédex

print("+-------------------------------------------------------------+")
print("|                                          October 11th, 2022 |")
print("|                                              Quito, Ecuador |")
print("|  Dear Self,                                                 |")
print("|                                                             |")
print("|      I feal like this is too easy for my level.             |")
print("|      I want to learn more Python.                           |")
print("|      Make more money.                                       |")
print("|                                                             |")
print("|                                                             |")
print("|                                            Carlitos         |")
print("|                                                             |")
print("+-------------------------------------------------------------+")
